def gen_subscription(
    secrets: bytes, device_id: int, start: int, end: int, channel: int
) -> bytes:
    """Generate the contents of a subscription.

    :param secrets: Secrets file generated by gen_secrets
    :param device_id: Decoder's device ID
    :param start: Subscription start timestamp
    :param end: Subscription end timestamp
    :param channel: Channel to enable
    """
    # TODO: Consider secure packing of subscription data. Use secrets to
    # validate the subscription before encoding it. Ensure subscription 
    # validity against secrets if needed.
    
    # Load the secrets from the provided file
    secrets = json.loads(secrets)

    # Pack the subscription data securely for the Decoder
    return struct.pack("<IQQI", device_id, start, end, channel)
